### ISSUE TITLE
[Question] Bridge Operator without Transactions

### ISSUE THREAD

**Issue by jmartins-sh** [axieinfinity/bridge-v2#98]
Hello folks, how's it going? 

I am trying to set up a new machine bridge node, but I don't know why there is no transaction shown yet when I check the transaction list page to the bridge address:

![image](https://github.com/axieinfinity/bridge-v2/assets/16046723/5a4c77d8-abef-44c4-8710-ef9d0463cea2)

I've already tried the discords and support, but sadly no one could help me out.

Have I done something wrong? I appreciate any help! :)

**Comment by minh-bq** [comment]
The bridge node only submits transaction when the bridge address is in bridge operator set. In this case, your bridge address is not in bridge operator set so you see no transaction.

**Comment by jmartins-sh** [comment]
Hey @minh-bq, how is it going? 

Thanks for the reply.

I see, I am pretty new in blockchain and stuff, there's anything that I have to do to be in the bridge operator set?

**Comment by minh-bq** [comment]
Hi @joaoantoniomartinsfilho,

To be in the bridge operator set, you must have approval of at least 70% current bridge governor.

**Comment by jmartins-sh** [comment]
Hey @minh-bq, thanks again for your answer, I took a look at the proposal flow, and looks like only bridge governors can open new proposals, so sadly I can't become a bridge node. Anyways thanks again, have a nice week!
